### PR TITLE
[SPARK-43351] Support more data types when reading from spark connect arrow dataset to data frame; Also implement CreateTempView

### PR DESCRIPTION
**Pull request by hiboyang**
### What changes were proposed in this pull request?

Support more data types when reading from spark connect arrow dataset to data frame; Also implement CreateTempView

### Why are the changes needed?

Support more data types when reading from spark connect arrow dataset to data frame; Also implement CreateTempView

### Does this PR introduce _any_ user-facing change?

Yes, able to create temp view, e.g. 
```
dataframe.CreateTempView(...)
```

### How was this patch tested?

Unit test, and also manual test by running example code

### CODE REVIEW

**Comment by hiboyang** [comment]
@grundprinzip @HyukjinKwon here is another PR for Go client :)

**Review by grundprinzip — COMMENTED** [review]
The change generally looks good, can you please check the coverage of your tests to see if your conversion routine is properly tested.

**Comment by hiboyang** [comment]
> The change generally looks good, can you please check the coverage of your tests to see if your conversion routine is properly tested.

Yes, added extra tests to cover unsupported data types. Now the coverage is 100% for the conversion routines.

**Comment by hiboyang** [comment]
@grundprinzip do you get time to take another look at this PR?

**Comment by grundprinzip** [comment]
Will do, it's been a hectic week here :)

**Review by grundprinzip — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by HyukjinKwon** [comment]
Should probably avoid using the same JIRA (https://issues.apache.org/jira/browse/SPARK-43351), but use a new sub-task JIRA ...

**Comment by hiboyang** [comment]
> Should probably avoid using the same JIRA (https://issues.apache.org/jira/browse/SPARK-43351), but use a new sub-task JIRA ...

Good suggestion! Will create sub task JIRA!

**Pull request closed without merging**
